FROM perl:5.42-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    libsqlite3-dev sqlite3 curl wget make gcc \
 && rm -rf /var/lib/apt/lists/*
RUN curl -fsSL https://cpanmin.us -o /usr/local/bin/cpanm \
 && chmod +x /usr/local/bin/cpanm \
 && cpanm --curl --notest \
      Test::Exception \
      Test::MockModule \
      Perl::Critic \
      Mojolicious \
      DBI \
      DBD::SQLite \
      LWP::UserAgent \
      JSON::XS \
      File::ShareDir \
      WebService::Plex \
 && rm -rf ~/.cpanm
WORKDIR /app
